# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpHOt2J7cNPg2qXC01zGYZwfouoIiMCz
"""

#app.py
import app1
import app2
import app3
import streamlit as st
PAGES = {
    "Client": app1,
    "Analysis": app2,
    "Predict": app3
}
st.sidebar.title('Navigation')
selection = st.sidebar.radio("Go to", list(PAGES.keys()))
page = PAGES[selection]
page.app()