# -*- coding: utf-8 -*-
"""app1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpHOt2J7cNPg2qXC01zGYZwfouoIiMCz
"""

# app1.py
import streamlit as st
def app():
    st.title('Trading Plateform')
    st.write('Welcome to our financial Trading Plateforme')