# -*- coding: utf-8 -*-
"""app2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpHOt2J7cNPg2qXC01zGYZwfouoIiMCz
"""

# app2.py
import streamlit as st
import pandas as pd
import pandas_datareader.data as web
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

now = datetime.now()
date_time = now.strftime("%Y-%m-%d")


def app():
    st.title('Predict')
    st.write('Ticker to predict')


#ticker= st.text_input("Ticker", value="Your Ticker")
#source= st.text_input("Source de donnée", value="Yoursource")
#datetime.date(1921, 1, 1)

##### Récupération de donnée

##### Récupération de donnée

toyota = web.DataReader('TM', data_source = "yahoo", start = "2013-04-04", end = date_time)
renault = web.DataReader('RNO.PA', data_source = "yahoo", start = "2013-04-04", end = date_time)
gm = web.DataReader('GM', data_source = "yahoo", start = "2013-04-04", end =  date_time)
stell = web.DataReader('STLA', data_source = "yahoo", start = "2013-04-04", end = date_time )
ford = web.DataReader('F', data_source = "yahoo", start = "2013-04-04", end = date_time)


##### Avoir le meme nombre de valeurs dans tout les dataset

toy_ren_join = toyota.merge(renault, how='left', on='Date') 
toy_ren_join


#### Récupération du cours de cloture

df = pd.concat([toy_ren_join['Close_x'],toy_ren_join['Close_y'], stell['Close'], gm['Close'], ford['Close']], axis =1) #### Concatenation des 5 valeurs de cloture

df.columns = [ "Toyota",'Renault',"Stellelantis", "GM", 'Ford']

#df.plot()

#toyota = web.DataReader(ticker, data_source = "yahoo", start = "2013-04-04", end = date_time)

st.line_chart(df)
#st.pyplot(toyota.Close.plot())

#### EN sortie
#( df.tail(2).iloc[0, 0] - df.iloc[0, 0] )/ df.iloc[0, 0]*100

