# -*- coding: utf-8 -*-
"""app3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpHOt2J7cNPg2qXC01zGYZwfouoIiMCz
"""

# app3.py
import streamlit as st
def app():
    st.title('Prédict')
    st.write('Welcome to app3')